{% set version = "2.0.2" %}

package:
  name: orderedset
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/orderedset/orderedset-{{ version }}.tar.gz
  sha256: 285ca273c7cdd545358b6e643160bd110117a221af7319740526b66ac1cb4bec

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - orderedset

about:
  home: https://github.com/simonpercivall/orderedset
  license: BSD 3-Clause
  license_file: LICENSE
  summary: An Ordered Set implementation in Cython.

extra:
  recipe-maintainers:
    - ocefpaf
